// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/admin" | "/admin/analytics" | "/admin/jurisprudence" | "/admin/modules" | "/admin/plans" | "/agents" | "/agents/jurisprudence" | "/announcements" | "/approvals/seals" | "/archive" | "/audit" | "/clients" | "/clients/[id]" | "/conflicts" | "/contacts" | "/dashboard" | "/express" | "/finance" | "/firm-resources" | "/inbox" | "/intakes" | "/intakes/[id]" | "/jurisprudence" | "/login" | "/matters" | "/matters/[id]" | "/notifications" | "/policy" | "/preservation" | "/privacidad" | "/register" | "/reports" | "/schedule" | "/seals" | "/settings" | "/settings/ai" | "/settings/audit" | "/settings/custom-fields" | "/settings/danger-zone" | "/settings/express" | "/settings/firm-profile" | "/settings/import" | "/settings/profile" | "/settings/reminders" | "/settings/stages" | "/settings/subscription" | "/settings/templates" | "/settings/users" | "/settings/writings" | "/terminos"
type AppRouteHandlerRoutes = "/api/announcements/sse" | "/api/archive/[matterId]/export" | "/api/archive/folder/[folderId]/download" | "/api/archive/matter/[matterId]/download" | "/api/auth/[...nextauth]" | "/api/calendar/[token]" | "/api/documents/[id]/download" | "/api/documents/[id]/preview" | "/api/firm-files/[id]/download" | "/api/health" | "/api/imports/matters/template" | "/api/matters/export" | "/api/reports/export"
type PageRoutes = never
type LayoutRoutes = "/" | "/admin" | "/settings"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/admin": {}
  "/admin/analytics": {}
  "/admin/jurisprudence": {}
  "/admin/modules": {}
  "/admin/plans": {}
  "/agents": {}
  "/agents/jurisprudence": {}
  "/announcements": {}
  "/api/announcements/sse": {}
  "/api/archive/[matterId]/export": { "matterId": string; }
  "/api/archive/folder/[folderId]/download": { "folderId": string; }
  "/api/archive/matter/[matterId]/download": { "matterId": string; }
  "/api/auth/[...nextauth]": { "nextauth": string[]; }
  "/api/calendar/[token]": { "token": string; }
  "/api/documents/[id]/download": { "id": string; }
  "/api/documents/[id]/preview": { "id": string; }
  "/api/firm-files/[id]/download": { "id": string; }
  "/api/health": {}
  "/api/imports/matters/template": {}
  "/api/matters/export": {}
  "/api/reports/export": {}
  "/approvals/seals": {}
  "/archive": {}
  "/audit": {}
  "/clients": {}
  "/clients/[id]": { "id": string; }
  "/conflicts": {}
  "/contacts": {}
  "/dashboard": {}
  "/express": {}
  "/finance": {}
  "/firm-resources": {}
  "/inbox": {}
  "/intakes": {}
  "/intakes/[id]": { "id": string; }
  "/jurisprudence": {}
  "/login": {}
  "/matters": {}
  "/matters/[id]": { "id": string; }
  "/notifications": {}
  "/policy": {}
  "/preservation": {}
  "/privacidad": {}
  "/register": {}
  "/reports": {}
  "/schedule": {}
  "/seals": {}
  "/settings": {}
  "/settings/ai": {}
  "/settings/audit": {}
  "/settings/custom-fields": {}
  "/settings/danger-zone": {}
  "/settings/express": {}
  "/settings/firm-profile": {}
  "/settings/import": {}
  "/settings/profile": {}
  "/settings/reminders": {}
  "/settings/stages": {}
  "/settings/subscription": {}
  "/settings/templates": {}
  "/settings/users": {}
  "/settings/writings": {}
  "/terminos": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
  "/admin": never
  "/settings": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
