// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../src/app/(app)/admin/analytics/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/analytics">> = Specific
  const handler = {} as typeof import("../../src/app/(app)/admin/analytics/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(app)/admin/jurisprudence/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/jurisprudence">> = Specific
  const handler = {} as typeof import("../../src/app/(app)/admin/jurisprudence/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(app)/admin/modules/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/modules">> = Specific
  const handler = {} as typeof import("../../src/app/(app)/admin/modules/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(app)/admin/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin">> = Specific
  const handler = {} as typeof import("../../src/app/(app)/admin/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(app)/admin/plans/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/plans">> = Specific
  const handler = {} as typeof import("../../src/app/(app)/admin/plans/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(app)/agents/jurisprudence/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/agents/jurisprudence">> = Specific
  const handler = {} as typeof import("../../src/app/(app)/agents/jurisprudence/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(app)/agents/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/agents">> = Specific
  const handler = {} as typeof import("../../src/app/(app)/agents/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(app)/announcements/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/announcements">> = Specific
  const handler = {} as typeof import("../../src/app/(app)/announcements/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(app)/approvals/seals/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/approvals/seals">> = Specific
  const handler = {} as typeof import("../../src/app/(app)/approvals/seals/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(app)/archive/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/archive">> = Specific
  const handler = {} as typeof import("../../src/app/(app)/archive/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(app)/audit/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/audit">> = Specific
  const handler = {} as typeof import("../../src/app/(app)/audit/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(app)/clients/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/clients/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/(app)/clients/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(app)/clients/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/clients">> = Specific
  const handler = {} as typeof import("../../src/app/(app)/clients/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(app)/conflicts/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/conflicts">> = Specific
  const handler = {} as typeof import("../../src/app/(app)/conflicts/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(app)/contacts/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/contacts">> = Specific
  const handler = {} as typeof import("../../src/app/(app)/contacts/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(app)/dashboard/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard">> = Specific
  const handler = {} as typeof import("../../src/app/(app)/dashboard/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(app)/express/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/express">> = Specific
  const handler = {} as typeof import("../../src/app/(app)/express/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(app)/finance/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/finance">> = Specific
  const handler = {} as typeof import("../../src/app/(app)/finance/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(app)/firm-resources/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/firm-resources">> = Specific
  const handler = {} as typeof import("../../src/app/(app)/firm-resources/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(app)/inbox/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/inbox">> = Specific
  const handler = {} as typeof import("../../src/app/(app)/inbox/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(app)/intakes/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/intakes/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/(app)/intakes/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(app)/intakes/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/intakes">> = Specific
  const handler = {} as typeof import("../../src/app/(app)/intakes/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(app)/jurisprudence/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/jurisprudence">> = Specific
  const handler = {} as typeof import("../../src/app/(app)/jurisprudence/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(app)/matters/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/matters/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/(app)/matters/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(app)/matters/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/matters">> = Specific
  const handler = {} as typeof import("../../src/app/(app)/matters/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(app)/notifications/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/notifications">> = Specific
  const handler = {} as typeof import("../../src/app/(app)/notifications/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(app)/policy/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/policy">> = Specific
  const handler = {} as typeof import("../../src/app/(app)/policy/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(app)/preservation/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/preservation">> = Specific
  const handler = {} as typeof import("../../src/app/(app)/preservation/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(app)/reports/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/reports">> = Specific
  const handler = {} as typeof import("../../src/app/(app)/reports/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(app)/schedule/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/schedule">> = Specific
  const handler = {} as typeof import("../../src/app/(app)/schedule/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(app)/seals/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/seals">> = Specific
  const handler = {} as typeof import("../../src/app/(app)/seals/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(app)/settings/ai/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/settings/ai">> = Specific
  const handler = {} as typeof import("../../src/app/(app)/settings/ai/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(app)/settings/audit/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/settings/audit">> = Specific
  const handler = {} as typeof import("../../src/app/(app)/settings/audit/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(app)/settings/custom-fields/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/settings/custom-fields">> = Specific
  const handler = {} as typeof import("../../src/app/(app)/settings/custom-fields/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(app)/settings/danger-zone/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/settings/danger-zone">> = Specific
  const handler = {} as typeof import("../../src/app/(app)/settings/danger-zone/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(app)/settings/express/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/settings/express">> = Specific
  const handler = {} as typeof import("../../src/app/(app)/settings/express/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(app)/settings/firm-profile/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/settings/firm-profile">> = Specific
  const handler = {} as typeof import("../../src/app/(app)/settings/firm-profile/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(app)/settings/import/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/settings/import">> = Specific
  const handler = {} as typeof import("../../src/app/(app)/settings/import/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(app)/settings/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/settings">> = Specific
  const handler = {} as typeof import("../../src/app/(app)/settings/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(app)/settings/profile/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/settings/profile">> = Specific
  const handler = {} as typeof import("../../src/app/(app)/settings/profile/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(app)/settings/reminders/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/settings/reminders">> = Specific
  const handler = {} as typeof import("../../src/app/(app)/settings/reminders/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(app)/settings/stages/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/settings/stages">> = Specific
  const handler = {} as typeof import("../../src/app/(app)/settings/stages/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(app)/settings/subscription/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/settings/subscription">> = Specific
  const handler = {} as typeof import("../../src/app/(app)/settings/subscription/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(app)/settings/templates/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/settings/templates">> = Specific
  const handler = {} as typeof import("../../src/app/(app)/settings/templates/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(app)/settings/users/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/settings/users">> = Specific
  const handler = {} as typeof import("../../src/app/(app)/settings/users/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(app)/settings/writings/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/settings/writings">> = Specific
  const handler = {} as typeof import("../../src/app/(app)/settings/writings/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(auth)/login/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/login">> = Specific
  const handler = {} as typeof import("../../src/app/(auth)/login/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(auth)/register/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/register">> = Specific
  const handler = {} as typeof import("../../src/app/(auth)/register/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(legal)/privacidad/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/privacidad">> = Specific
  const handler = {} as typeof import("../../src/app/(legal)/privacidad/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(legal)/terminos/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/terminos">> = Specific
  const handler = {} as typeof import("../../src/app/(legal)/terminos/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/announcements/sse/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/announcements/sse">> = Specific
  const handler = {} as typeof import("../../src/app/api/announcements/sse/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/archive/[matterId]/export/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/archive/[matterId]/export">> = Specific
  const handler = {} as typeof import("../../src/app/api/archive/[matterId]/export/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/archive/folder/[folderId]/download/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/archive/folder/[folderId]/download">> = Specific
  const handler = {} as typeof import("../../src/app/api/archive/folder/[folderId]/download/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/archive/matter/[matterId]/download/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/archive/matter/[matterId]/download">> = Specific
  const handler = {} as typeof import("../../src/app/api/archive/matter/[matterId]/download/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/auth/[...nextauth]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/[...nextauth]">> = Specific
  const handler = {} as typeof import("../../src/app/api/auth/[...nextauth]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/calendar/[token]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/calendar/[token]">> = Specific
  const handler = {} as typeof import("../../src/app/api/calendar/[token]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/documents/[id]/download/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/documents/[id]/download">> = Specific
  const handler = {} as typeof import("../../src/app/api/documents/[id]/download/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/documents/[id]/preview/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/documents/[id]/preview">> = Specific
  const handler = {} as typeof import("../../src/app/api/documents/[id]/preview/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/firm-files/[id]/download/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/firm-files/[id]/download">> = Specific
  const handler = {} as typeof import("../../src/app/api/firm-files/[id]/download/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/health/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/health">> = Specific
  const handler = {} as typeof import("../../src/app/api/health/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/imports/matters/template/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/imports/matters/template">> = Specific
  const handler = {} as typeof import("../../src/app/api/imports/matters/template/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/matters/export/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/matters/export">> = Specific
  const handler = {} as typeof import("../../src/app/api/matters/export/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/reports/export/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/reports/export">> = Specific
  const handler = {} as typeof import("../../src/app/api/reports/export/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../src/app/(app)/admin/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/admin">> = Specific
  const handler = {} as typeof import("../../src/app/(app)/admin/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(app)/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/(app)/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(app)/settings/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/settings">> = Specific
  const handler = {} as typeof import("../../src/app/(app)/settings/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(auth)/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/(auth)/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(legal)/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/(legal)/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
