var R=require("../../../chunks/ssr/[turbopack]_runtime.js")("server/app/(auth)/register/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__089eiz1._.js")
R.c("server/chunks/ssr/1rdk_next_dist_esm_build_templates_app-page_11-wgbq.js")
R.c("server/chunks/ssr/[root-of-the-server]__1c6gk3v._.js")
R.c("server/chunks/ssr/1rdk_next_dist_1biagn7._.js")
R.c("server/chunks/ssr/1rdk_next_dist_compiled_@opentelemetry_api_index_1466mq2.js")
R.c("server/chunks/ssr/lawlink_src_0thdlsy._.js")
R.c("server/chunks/ssr/1rdk_next_dist_client_components_0jaxoi1._.js")
R.c("server/chunks/ssr/1rdk_next_dist_client_components_builtin_forbidden_02l0zfk.js")
R.c("server/chunks/ssr/1rdk_next_dist_client_components_builtin_unauthorized_08cl0_3.js")
R.c("server/chunks/ssr/1rdk_next_dist_client_components_builtin_global-error_0tfzn54.js")
R.c("server/chunks/ssr/lawlink_src_app_(auth)_layout_tsx_0kcs29y._.js")
R.c("server/chunks/ssr/[root-of-the-server]__146vq1t._.js")
R.c("server/chunks/ssr/lawlink_184czpm._.js")
R.c("server/chunks/ssr/1rdk_next_dist_0s9bk21._.js")
R.m(609593)
module.exports=R.m(609593).exports
