/**
 * v0.9.4 å½’æ¡£å¿…äº¤ææ–™ checklist
 *
 * ä¸‰å¥—æ¸…å•æŒ‰ Matter.category æ˜ å°„ï¼š
 *   - è¯‰è®¼ç±»ï¼ˆæ°‘å•†/Penal/Administrativoï¼‰â†’ LITIGATION
 *   - éžè¯‰ / ä¸“Ã­tems â†’ NON_LITIGATION
 *   - é¡¾é—® â†’ LEGAL_COUNSEL
 *
 * required=true çš„Ã­temsç¼ºå¤±ä¼šåœ¨å½’æ¡£Confirmaré¡µæŠ¥è­¦å‘Šï¼ˆä¸é˜»æ–­ï¼ŒAbogadoå¯å¼ºåˆ¶å½’æ¡£ä½†éœ€è®°å…¥ missingItemsï¼‰ã€‚
 * autoGenerated=true çš„Ã­temsç”±Sistemaåœ¨å½’æ¡£æ—¶è‡ªåŠ¨ç”Ÿæˆï¼ˆå°çš® / ç›®å½•ï¼‰ï¼ŒAbogadoæ— é¡»æ‰‹åŠ¨å‹¾é€‰ã€‚
 */
import type { MatterCategory } from "@prisma/client";

export type ArchiveChecklistKind =
  | "LITIGATION"
  | "NON_LITIGATION"
  | "LEGAL_COUNSEL";

export interface ArchiveChecklistItem {
  id: string;
  label: string;
  required: boolean;
  autoGenerated?: boolean;
  hint?: string;
}

export interface ArchiveChecklist {
  kind: ArchiveChecklistKind;
  title: string;
  items: ArchiveChecklistItem[];
}

const LITIGATION: ArchiveChecklist = {
  kind: "LITIGATION",
  title: "Lista de archivo del caso de litigio",
  items: [
    {
      id: "retainer_contract",
      label: "Contrato de representaciÃ³n legal",
      required: true,
    },
    {
      id: "power_of_attorney",
      label: "Poder de representaciÃ³n",
      required: true,
    },
    {
      id: "risk_disclosure",
      label: "Documento de advertencia de riesgos",
      required: false,
    },
    {
      id: "intake_form",
      label: "Formulario de ingreso del caso",
      required: false,
    },
    {
      id: "pleading",
      label: "Demanda / contestaciÃ³n / apelaciÃ³n",
      required: true,
      hint: "Basta con enviar una copia segÃºn nuestra posiciÃ³n",
    },
    {
      id: "evidence_catalog",
      label: "CatÃ¡logo de evidencia y materiales probatorios",
      required: true,
    },
    {
      id: "hearing_record",
      label: "Acta de audiencia / conversaciÃ³n / revisiÃ³n de expediente",
      required: false,
    },
    {
      id: "agent_opinion",
      label: "Alegato / carta del abogado",
      required: false,
    },
    {
      id: "judgment",
      label: "Documento judicial (sentencia / auto / acta de conciliaciÃ³n)",
      required: true,
    },
    {
      id: "closing_form",
      label: "Formulario de cierre del caso",
      required: true,
    },
    { id: "case_summary", label: "Resumen del caso", required: true },
    { id: "fee_receipt", label: "Comprobante de pago", required: false },
    {
      id: "archive_cover",
      label: "Portada del expediente",
      required: true,
      autoGenerated: true,
    },
    {
      id: "archive_catalog",
      label: "Ãndice del expediente",
      required: true,
      autoGenerated: true,
    },
  ],
};

const NON_LITIGATION: ArchiveChecklist = {
  kind: "NON_LITIGATION",
  title: "Lista de archivo de no contencioso / proyectos especiales",
  items: [
    {
      id: "retainer_contract",
      label: "Contrato de representaciÃ³n legal",
      required: true,
    },
    {
      id: "intake_form",
      label: "Formulario de ingreso del caso",
      required: false,
    },
    {
      id: "legal_opinion",
      label: "Informe de investigaciÃ³n / dictamen legal",
      required: true,
    },
    { id: "working_papers", label: "Documentos de trabajo", required: false },
    {
      id: "issued_documents",
      label:
        "Documentos legales emitidos (dictÃ¡menes de revisiÃ³n contractual / certificaciÃ³n del abogado / informe de due diligence, etc.)",
      required: true,
    },
    {
      id: "client_confirmation",
      label: "Carta de confirmaciÃ³n del cliente / materiales de aceptaciÃ³n",
      required: false,
    },
    {
      id: "closing_form",
      label: "Formulario de cierre del caso",
      required: true,
    },
    { id: "case_summary", label: "Resumen del caso", required: true },
    { id: "fee_receipt", label: "Comprobante de pago", required: false },
    {
      id: "archive_cover",
      label: "Portada del expediente",
      required: true,
      autoGenerated: true,
    },
    {
      id: "archive_catalog",
      label: "Ãndice del expediente",
      required: true,
      autoGenerated: true,
    },
  ],
};

const LEGAL_COUNSEL: ArchiveChecklist = {
  kind: "LEGAL_COUNSEL",
  title: "Lista de archivo de asesorÃ­a legal",
  items: [
    {
      id: "counsel_contract",
      label: "Contrato de asesorÃ­a legal",
      required: true,
    },
    {
      id: "consultation_log",
      label: "Registro consolidado de consultas",
      required: false,
    },
    {
      id: "legal_opinions_compendium",
      label: "DictÃ¡menes legales emitidos / cartas del abogado consolidadas",
      required: true,
    },
    {
      id: "contract_reviews",
      label: "Opiniones consolidadas de revisiÃ³n contractual",
      required: false,
    },
    {
      id: "training_records",
      label: "Registros de capacitaciÃ³n",
      required: false,
    },
    { id: "fee_receipt", label: "Comprobante de pago", required: false },
    {
      id: "term_summary",
      label: "Resumen de cierre / renovaciÃ³n / terminaciÃ³n",
      required: true,
    },
    {
      id: "archive_cover",
      label: "Portada del expediente",
      required: true,
      autoGenerated: true,
    },
    {
      id: "archive_catalog",
      label: "Ãndice del expediente",
      required: true,
      autoGenerated: true,
    },
  ],
};

const CHECKLISTS: Record<ArchiveChecklistKind, ArchiveChecklist> = {
  LITIGATION,
  NON_LITIGATION,
  LEGAL_COUNSEL,
};

export function checklistForCategory(
  category: MatterCategory,
): ArchiveChecklist {
  switch (category) {
    case "CIVIL_COMMERCIAL":
    case "CRIMINAL":
    case "ADMINISTRATIVE":
      return LITIGATION;
    case "NON_LITIGATION":
    case "SPECIAL_PROJECT":
      return NON_LITIGATION;
    case "LEGAL_COUNSEL":
      return LEGAL_COUNSEL;
    default:
      return LITIGATION;
  }
}

export function getChecklist(kind: ArchiveChecklistKind): ArchiveChecklist {
  return CHECKLISTS[kind];
}

/**
 * è¯„ä¼°å‹¾é€‰Estadoï¼šVolverç¼ºÃ­tems + æ˜¯å¦é˜»æ–­è­¦å‘Š
 */
export function evaluateChecklist(
  checklist: ArchiveChecklist,
  checked: Record<string, boolean>,
): {
  missingRequired: ArchiveChecklistItem[];
  missingOptional: ArchiveChecklistItem[];
} {
  const missingRequired: ArchiveChecklistItem[] = [];
  const missingOptional: ArchiveChecklistItem[] = [];
  for (const item of checklist.items) {
    if (item.autoGenerated) continue;
    if (checked[item.id]) continue;
    if (item.required) missingRequired.push(item);
    else missingOptional.push(item);
  }
  return { missingRequired, missingOptional };
}

