/**
 * v0.9.4 归档必交材料 checklist
 *
 * 三套清单按 Matter.category 映射：
 *   - 诉讼类（民商/Penal/Administrativo）→ LITIGATION
 *   - 非诉 / 专ítems → NON_LITIGATION
 *   - 顾问 → LEGAL_COUNSEL
 *
 * required=true 的ítems缺失会在归档Confirmar页报警告（不阻断，Abogado可强制归档但需记入 missingItems）。
 * autoGenerated=true 的ítems由Sistema在归档时自动生成（封皮 / 目录），Abogado无须手动勾选。
 */
import type { MatterCategory } from "@prisma/client";

export type ArchiveChecklistKind =
  | "LITIGATION"
  | "NON_LITIGATION"
  | "LEGAL_COUNSEL";

export interface ArchiveChecklistItem {
  id: string;
  label: string;
  required: boolean;
  autoGenerated?: boolean;
  hint?: string;
}

export interface ArchiveChecklist {
  kind: ArchiveChecklistKind;
  title: string;
  items: ArchiveChecklistItem[];
}

const LITIGATION: ArchiveChecklist = {
  kind: "LITIGATION",
  title: "Lista de archivo del caso de litigio",
  items: [
    {
      id: "retainer_contract",
      label: "Contrato de representación legal",
      required: true,
    },
    {
      id: "power_of_attorney",
      label: "Poder de representación",
      required: true,
    },
    {
      id: "risk_disclosure",
      label: "Documento de advertencia de riesgos",
      required: false,
    },
    {
      id: "intake_form",
      label: "Formulario de ingreso del caso",
      required: false,
    },
    {
      id: "pleading",
      label: "Demanda / contestación / apelación",
      required: true,
      hint: "Basta con enviar una copia según nuestra posición",
    },
    {
      id: "evidence_catalog",
      label: "Catálogo de evidencia y materiales probatorios",
      required: true,
    },
    {
      id: "hearing_record",
      label: "Acta de audiencia / conversación / revisión de expediente",
      required: false,
    },
    {
      id: "agent_opinion",
      label: "Alegato / carta del abogado",
      required: false,
    },
    {
      id: "judgment",
      label: "Documento judicial (sentencia / auto / acta de conciliación)",
      required: true,
    },
    {
      id: "closing_form",
      label: "Formulario de cierre del caso",
      required: true,
    },
    { id: "case_summary", label: "Resumen del caso", required: true },
    { id: "fee_receipt", label: "Comprobante de pago", required: false },
    {
      id: "archive_cover",
      label: "Portada del expediente",
      required: true,
      autoGenerated: true,
    },
    {
      id: "archive_catalog",
      label: "Índice del expediente",
      required: true,
      autoGenerated: true,
    },
  ],
};

const NON_LITIGATION: ArchiveChecklist = {
  kind: "NON_LITIGATION",
  title: "Lista de archivo de no contencioso / proyectos especiales",
  items: [
    {
      id: "retainer_contract",
      label: "Contrato de representación legal",
      required: true,
    },
    {
      id: "intake_form",
      label: "Formulario de ingreso del caso",
      required: false,
    },
    {
      id: "legal_opinion",
      label: "Informe de investigación / dictamen legal",
      required: true,
    },
    { id: "working_papers", label: "Documentos de trabajo", required: false },
    {
      id: "issued_documents",
      label:
        "Documentos legales emitidos (dictámenes de revisión contractual / certificación del abogado / informe de due diligence, etc.)",
      required: true,
    },
    {
      id: "client_confirmation",
      label: "Carta de confirmación del cliente / materiales de aceptación",
      required: false,
    },
    {
      id: "closing_form",
      label: "Formulario de cierre del caso",
      required: true,
    },
    { id: "case_summary", label: "Resumen del caso", required: true },
    { id: "fee_receipt", label: "Comprobante de pago", required: false },
    {
      id: "archive_cover",
      label: "Portada del expediente",
      required: true,
      autoGenerated: true,
    },
    {
      id: "archive_catalog",
      label: "Índice del expediente",
      required: true,
      autoGenerated: true,
    },
  ],
};

const LEGAL_COUNSEL: ArchiveChecklist = {
  kind: "LEGAL_COUNSEL",
  title: "Lista de archivo de asesoría legal",
  items: [
    {
      id: "counsel_contract",
      label: "Contrato de asesoría legal",
      required: true,
    },
    {
      id: "consultation_log",
      label: "Registro consolidado de consultas",
      required: false,
    },
    {
      id: "legal_opinions_compendium",
      label: "Dictámenes legales emitidos / cartas del abogado consolidadas",
      required: true,
    },
    {
      id: "contract_reviews",
      label: "Opiniones consolidadas de revisión contractual",
      required: false,
    },
    {
      id: "training_records",
      label: "Registros de capacitación",
      required: false,
    },
    { id: "fee_receipt", label: "Comprobante de pago", required: false },
    {
      id: "term_summary",
      label: "Resumen de cierre / renovación / terminación",
      required: true,
    },
    {
      id: "archive_cover",
      label: "Portada del expediente",
      required: true,
      autoGenerated: true,
    },
    {
      id: "archive_catalog",
      label: "Índice del expediente",
      required: true,
      autoGenerated: true,
    },
  ],
};

const CHECKLISTS: Record<ArchiveChecklistKind, ArchiveChecklist> = {
  LITIGATION,
  NON_LITIGATION,
  LEGAL_COUNSEL,
};

export function checklistForCategory(
  category: MatterCategory,
): ArchiveChecklist {
  switch (category) {
    case "CIVIL_COMMERCIAL":
    case "CRIMINAL":
    case "ADMINISTRATIVE":
      return LITIGATION;
    case "NON_LITIGATION":
    case "SPECIAL_PROJECT":
      return NON_LITIGATION;
    case "LEGAL_COUNSEL":
      return LEGAL_COUNSEL;
    default:
      return LITIGATION;
  }
}

export function getChecklist(kind: ArchiveChecklistKind): ArchiveChecklist {
  return CHECKLISTS[kind];
}

/**
 * 评估勾选Estado：Volver缺ítems + 是否阻断警告
 */
export function evaluateChecklist(
  checklist: ArchiveChecklist,
  checked: Record<string, boolean>,
): {
  missingRequired: ArchiveChecklistItem[];
  missingOptional: ArchiveChecklistItem[];
} {
  const missingRequired: ArchiveChecklistItem[] = [];
  const missingOptional: ArchiveChecklistItem[] = [];
  for (const item of checklist.items) {
    if (item.autoGenerated) continue;
    if (checked[item.id]) continue;
    if (item.required) missingRequired.push(item);
    else missingOptional.push(item);
  }
  return { missingRequired, missingOptional };
}
